### ISSUE TITLE
Insert notice before any existing header comments?

### ISSUE THREAD

**Issue by claydiffrient** [nickdeis/eslint-plugin-notice#1]
It seems that when using `--fix` this will insert the header below already existing block level comments.

For example before fixing:
```
/**
 * This file contains important variables used throughout the project
 */
```
Then after fixing it would look like this:
```
/**
 * This file contains important variables used throughout the project
 */

/**
 * Copyright (c) 2017 Acme Corp.
 */
```

whereas I would expect it to look like this:
```
/**
 * Copyright (c) 2017 Acme Corp.
 */

/**
 * This file contains important variables used throughout the project
 */
```

**Comment by nickdeis** [comment]
Hey Clay,
Thanks for raising this issue! I think you are correct that should be the behavior. I'll see what I can do about it.

**Comment by nickdeis** [comment]
Hey Clay,
So I fix'd it and published it. Tell me how it goes!
