### ISSUE TITLE
Use `templateFile` only

### ISSUE THREAD

**Issue by moshest** [nickdeis/eslint-plugin-notice#2]
I think it would make sense to use only the `templateFile` parameter and supply for each argument such as `YEAR` a matching regex pattern.

**Comment by nickdeis** [comment]
Hey moshest,
A little confused here. Are you saying that `templateFile` should be the `mustMatch` as well?
That's a pretty good idea, but the reason I made it the way I did was that I wanted to allow different copyright headers (different years, different companies) to be allowed to match a regex that would probably be more complicated than `templateFile` itself.
Maybe I could look into making it default to this behavior if `mustMatch` or `chars` is null.
If I misread that, please say so.
Best,
Nick

**Comment by moshest** [comment]
A little code will help, here is what I use in my `.eslintrc.js` file:

```js
const fs = require('fs');
const escapeStringRegexp = require('escape-string-regexp');

const copyrightTemplate = fs.readFileSync(`${__dirname}/config/copyright.js`).toString();
const copyrightMatch = escapeStringRegexp(copyrightTemplate).replace('<%= YEAR %>', '20\\d\\d');

module.exports = {
  plugins: ['notice'],

  rules: {
    'notice/notice': ['error',
      {
        mustMatch: copyrightMatch,
        template: copyrightTemplate,
      },
    ],
  },
};
```

**Comment by nickdeis** [comment]
Hey moshest,
That's actually pretty cool.
Perhaps the default for `mustMatch` is that it reads the template and replaces `YEAR` with `\\d{4}`. Users can define other variables though, so I don't know how well that would work.
What do you think?

**Comment by moshest** [comment]
I think that if `template` or `templateFile` exists, `mustMatch` can be optional. If `mustMatch` is optional, then the user must supply for each variable a RegExp.

**Comment by nickdeis** [comment]
Hey @moshest,
I like that idea. I'd want to YEAR to have a default regexp included. Since it's your idea, would you like to implement this? If not I'd be happy to do it.
Best,
Nick

**Comment by moshest** [comment]
I think I would be better if you implement it. It's involving update the documentation, breaks backward competability, tests and many more changes so you will do it better.

You can use the code I attach on the above [comment](https://github.com/nickdeis/eslint-plugin-notice/issues/2#issuecomment-322574823).

**Comment by nickdeis** [comment]
Hey @moshest,
Added this in 0.4.4 to make it easier to test for issue #3. 

## Usage
or just use your template, eslint-plugin-notice will reverse into a pattern for `mustMatch`

```json
{
    "notice/notice":["error",
        {
        "templateFile":"config/copyright.js"
        }
    ]
}
```

Want a more expressive template? Add `templateVars` and `varRegexps`
*config/copyright.js*
```js
/**
 * Copyright (c) <%= YEAR %>, <%= NAME %>
 */
```
```js
{
    "notice/notice":["error",
        {
        templateFile:"config/copyright.js",
        //YEAR will still be added unless you add your own value
        templateVars:{NAME:"Nick Deis"},
        //The regexp for YEAR is /20\d{2}/ and is automatically added
        varRegexps:{NAME:/(Nick|Nicholas) Deis/}
        }
    ]
}
```

Tell me how it goes!
Nick

**Comment by moshest** [comment]
Well, first of all you have a bug.

You should `.replace('<%= YEAR %>', '20\\d\\d')` but instead you're doing `.replace('<%= YEAR %>', '\\/20\\d\\d\\/')`.

(I compared the template generated from my file and yours).

**Comment by nickdeis** [comment]
Good catch. I do find it odd that my unit tests are passing, but I keep running into issues with the eslint test-suite so I guess I'm not surprised. 
Thanks for reviewing my code!
Nick

**Comment by nickdeis** [comment]
Alright, so I started testing things outside of the eslint test suite to confirm issues better, I hope this works!
Best,
Nick

**Comment by nickdeis** [comment]
Closing issue. Please reopen if you run into any problems.
