### ISSUE TITLE
Check for an existing notice that is close, but incorrect

### ISSUE THREAD

**Issue by Graham42** [nickdeis/eslint-plugin-notice#4]
I've run into a case where some files had a notice, but with incorrect capitalisation, missing punctuation, or typo. This leads to duplicate notices when using `--fix`

It would be great to have a "closeness" metric/threshold that would allow for fixing notices with typos or other problems.

Example:
```
/* Copyright (c) 2014-present, Foo bar Inc. */
```
vs
```
/* Copyright (c) 2014-present, FooBar, Inc. */
```

For some users there would be some edge cases like not wanting to change the initial year.

**Comment by nickdeis** [comment]
Hey @Graham42, thanks for filing this detailed issue 👍 
This is actually a cool idea. Haven't done any work with n-grams in js, so this might be fun.
Are you telling me this would be more useful for people who large codebases which have so many variations of copyrights that a regexp may not be useful to them? I'm just formulating the user story here.
Cheers,
Nick

**Comment by Graham42** [comment]
Yep, that's accurate.

**Comment by nickdeis** [comment]
So in that case, it should look at the distance between the resolved template and the existing header characters/header comment.
Do you have any interest in implementing this? 
If not I'll probably do it.
Best,
Nick

**Comment by Graham42** [comment]
Not at this point in time. Go for it :)

**Comment by nickdeis** [comment]
Hey @Graham42, 
This has been added in v0.5.5.
See the config option  `nonMatchingTolerance`.
Tell me how this works out for you 😄.
Best,
Nick

**Comment by retorquere** [comment]
Does this rule still warn (but not fix) if it isn't an exact match?

**Comment by nickdeis** [comment]
Hey @retorquere, 
Great question!
Depends on how it's configured, see [onNonMatchingHeader](https://github.com/nickdeis/eslint-plugin-notice#onnonmatchingheader)
