### ISSUE TITLE
no such file or directory

### ISSUE THREAD

**Issue by FDiskas** [nickdeis/eslint-plugin-notice#5]
```
"notice/notice": [
      "error",
      {
        "mustMatch":
          "[0-9]{0,4} All rights reserved.",
        "templateFile": "config/copyright.js",
        "nonMatchingTolerance": ".70"
      }
    ]
```
```Error while loading rule 'notice/notice'/mnt/SSD/Projects/.../src/modules/searchModule.js:: ENOENT/mnt/SSD/Projects/.../src/modules/searchModule.js:: no such file or directory, open 'config/copyright.js'```
And yes - the file is under the root folder in config directory
```
eslint-plugin-notice@0.5.6
```

**Comment by FDiskas** [comment]
As a workaround i used inline template with new line symbols
```json
"notice/notice": [
      "error",
      {
        "mustMatch":
          "[0-9]{0,4} All rights reserved.",
        "template":
          "/**\n * Copyright (C) <%= YEAR %> All rights reserved.\n */\n",
        "nonMatchingTolerance": ".70"
      }
    ]
```
:railway_car:

**Comment by nickdeis** [comment]
Hey Vytenis,
Thank you for filing an issue. 
Could you give me an idea about how your directories are structured?
How are you calling eslint?
Where in the directory structure are you calling eslint?
Sorry about the hassle,
Nick

**Comment by FDiskas** [comment]
Other plugins are using strange solutions for this problem 
https://github.com/benmosher/eslint-plugin-import/blob/a69b77181c423043d39f1c8752b296aaa95facfc/resolvers/webpack/index.js
My folder structure is ![structure](https://i.imgur.com/Vy3m6uT.png)
and in that "config" directory was that file. Eslint is integrated in VSCode, same as in PHPStorm all of them are showing errors like can't find. :tada:

**Comment by nickdeis** [comment]
Ahhh I see the issue now. Thank you for all your input/help.
So I don't think eslint-plugin-import is that strange of an approach, it's basically the approach I would take. However, I think the file path should point to the root of the eslint file, not package.json.
In practice, this will almost always be the same root.
I'm going to look into if the eslint API has some sort of reference to the root eslint file or the location of eslint config (probably not) but if not I'll probably make some sort of find-root kind algorithm.
You seem keen on implementing this, and I typically ask the reporter of the issue if they would like to implement the fix, but if not, I'll get to this sometime tommorrow.
Cheers,
Nick

**Comment by FDiskas** [comment]
@nickdeis - yes do it, I tried with no success. Did't know allot stuff about eslint API. And to write tests for this would be imposible for me :)

**Comment by nickdeis** [comment]
I think I have to use package.json, eslint has too many config formats, and they are expanding them in the future.
Also, I'm hoping that vscode sends the content via the file itself and not stdin.

**Comment by nickdeis** [comment]
Alright, I hopefully fixed the issue in version 0.6.6, but if not, the error messages should be more useful.
Thanks,
Nick

**Comment by FDiskas** [comment]
Thanks. I will test it

**Comment by FDiskas** [comment]
works

**Comment by nickdeis** [comment]
Thank you!
