### ISSUE TITLE
Make error text more helpful?

### ISSUE THREAD

**Issue by bevacqua** [nickdeis/eslint-plugin-notice#8]
Would be better if it were configurable, or if it included a suggested fix:

- `Could not find a match for the mustMatch pattern. Are you missing the header text?  notice/notice`
- Alternatively, make it configurable

```
notice/notice:
  - error
  - errorMessage: 'Missing license header'
  - templateFile: config/copyright.js
```

**Comment by nickdeis** [comment]
Hey @bevacqua,
Thanks for filing an issue.
I like this idea a lot. There is a lot of information not being displayed to the user which may help them debug a header issue. An issue a ran into recently was trying to figure out why a big license header wasn't near enough to the template using the `nonMatchingTolerance` setting. Might of been useful to see what the edit distance was in the error message.
Hence, I'll probably make it configurable with good defaults. Not sure what those will be so if you have any idea about what you want to see in terms of available template variables or defaults feel free to pitch it.
Best,
Nick
PS: Huge fan of your writing!

**Comment by bevacqua** [comment]
Thanks!

I think the ability to set a custom message (I'd say plain text, but I guess you could later make it into a template if you think that's worthwhile) plus a default other than `Could not find a match for the mustMatch pattern.` which is not very descriptive would really help.

Maybe default to `Missing notice header`, which is closer to what other lint rules do? (It took me a bit to figure out the rule came from `notice/notice`, because the message itself was cryptic. Kind of like if the `no-semi` rule talked about tokens not being what it expected instead of just saying "missing semicolon")

**Comment by nickdeis** [comment]
Great suggestions!
`Missing notice header` is probably the most appropriate when it fails to match, because often there is other stuff in a header. 
For `nonMatchingTolerance` it can be a bit more complicated. Something like `Found a header comment which was too different from the required notice header ({{ dist }})`.
The other case of finding a header comment and choosing to fail would stay as is (`Found a header comment which did not have a notice header, skipping fix and reporting`).
Thanks for the help!

**Comment by nickdeis** [comment]
Changes are in version 0.7.7.
Relevant documentation

### messages

The `messages` option allows you to change the default error messages. 
There are three messages you can change by passing in an object with the pairs you wish to change. 
For example, if you want to change the default message for when a header does not match `mustMatch`:

```js
{
    "notice/notice":["error",
        {
            "mustMatch":"Apache License",
            "templateFile":"config/apache.js",
            "messages":{
                "whenFailedToMatch":"Couldn't find 'Apache License', are you sure you added it?"
            }
        }
    ]
}
```

The three configurable messages are: 

* **whenFailedToMatch**: When the header fails to match the `mustMatch` pattern.
* **reportAndSkip**: When using `"onNonMatchingHeader":"report"` and a non-matching notice is found.
* **whenOutsideTolerance**: When you using `nonMatchingTolerance` to check for notice similarity and it fails to be similar enough. Passes in `similarity` as a template variable (eg `"The similarity is {{ similarity }}"`)
